### ISSUE TITLE
Youtube ads neither skipper nor muted on CC with Google TV

### ISSUE THREAD

**Issue by schumi4** [gabe565/CastSponsorSkip#27]
The ads don't show up in the log or mute/skip, skipping segments works though. Casting to Chromecast with Google TV (or Android TV, it also needs a Youtube API key). Older 'standard' Chromecasts on same network work fine.

**Comment by gabe565** [comment]
Interesting. I'm also using a Chromecast with Google TV and it worked last I checked...hopefully something didn't change in the Cast API. I'll see if I can replicate this! 

Could you set `CSS_LOG_LEVEL=debug` to see if anything useful gets logged?

**Comment by gabe565** [comment]
Thanks, that's helpful. Sounds like ads aren't being detected for your device. Still planning to try to replicate!

**Comment by pengi** [comment]
I got the same issue when testing. This is the log I got (with actual video title removed though, but it was the title of the video I watched, so it detected it)

My comments inline for what I did

```
time=2023-10-02T20:30:57.493Z level=INFO msg="CastSponsorSkip v0.5.0 (73d1f7a)"
time=2023-10-02T20:30:57.494Z level=INFO msg="Searching for devices..."
time=2023-10-02T20:30:57.799Z level=INFO msg="Connected to cast device." device="Living Room TV"
time=2023-10-02T20:30:58.299Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-02T20:31:08.369Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-02T20:31:18.513Z level=DEBUG msg=Update device="Living Room TV"

Started video

time=2023-10-02T20:31:18.647Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-10-02T20:31:18.647Z level=DEBUG msg="Searching for video ID" query="\"--video title here--\""
time=2023-10-02T20:31:19.256Z level=DEBUG msg="Searching for video ID" query="\"--video title here--\""
time=2023-10-02T20:31:20.297Z level=DEBUG msg="Searching for video ID" query="\"--video title here--\""

Entered a segment of ads, nothing skipped

time=2023-10-02T20:31:22.339Z level=DEBUG msg="Searching for video ID" query="\"--video title here--\""
time=2023-10-02T20:31:26.378Z level=DEBUG msg="Searching for video ID" query="\"--video title here--\""
```

I'm testing with:
```
[Service]
Environment="CSS_PAUSED_INTERVAL=10s"
Environment="CSS_YOUTUBE_API_KEY=--api key--"
Environment="CSS_LOG_LEVEL=debug"
```

**Comment by gabe565** [comment]
I've been doing some testing and so far ad skip works reliably on a Chromecast Ultra and a Nest Hub. I don't think this is due to the device type, but I have another thought.

@pengi Your log made me realize the retry logic for the YouTube search might be getting in the way of ad skip. When a video is found, it will print a log with the video information, but that never showed up in your log and instead it kept retrying. This is currently expected. If the YouTube search fails, it will pause the update cycle and retry up to 10 times with an exponential backoff. Could you let that search happen 10 times and see if an error is printed?

It seems like I should improve the retry logic, and I should also log the first error instead of waiting for the last. I may change it to just log every error. That could get chatty but I think more info would have more easily shown what's going on here.

**Comment by gabe565** [comment]
I just found a couple more bugs that could be contributing to this:
1. When the YouTube search fails, the update interval is changed to the slower "paused" interval. I originally added this before ad skip was supported. It is only causing issues now so I'll remove it.
2. If the YouTube search returns no videos, the log message is suppressed. This seemed to make sense at first, but I'd rather that get logged.
I'll fix all of this and release an update soon. Hopefully it helps 🤞

**Comment by pengi** [comment]
Yeah, it definitely looks like exponential backoff, and it seems to stop after 10 times. But no comment afterwards.

I'm trying to setup a go development environment here too to see if I can investigate a bit myself, but meanwhile, here is the log.

```
time=2023-10-03T06:45:24.116Z level=INFO msg="CastSponsorSkip v0.5.0 (73d1f7a)"
time=2023-10-03T06:45:24.117Z level=INFO msg="Searching for devices..."
time=2023-10-03T06:45:24.264Z level=INFO msg="Connected to cast device." device="Living Room TV"
time=2023-10-03T06:45:24.766Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T06:45:30.976Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T06:45:40.996Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T06:45:41.079Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-10-03T06:45:41.079Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:45:41.706Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:45:42.745Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:45:44.783Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:45:48.810Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:45:56.880Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:46:12.948Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:46:45.009Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:47:49.048Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:49:57.091Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:50:24.329Z level=DEBUG msg="Ignoring device." device="Living Room TV" reason="Already connected"
```

I also have a run where the "ignoring device" happened before the last "searching for video id"

```
time=2023-10-03T06:40:41.894Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-10-03T06:40:41.894Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:40:42.496Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:40:43.539Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:40:45.586Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:40:49.657Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:40:57.685Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:41:13.758Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:41:45.788Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:42:49.828Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T06:44:29.198Z level=DEBUG msg="Ignoring device." device="Living Room TV" reason="Already connected"
time=2023-10-03T06:44:57.901Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
```

In both runs, the retries was longer than the video clip itself, so had to scroll back a couple of times during playback, but that didn't seem to reset anything for what I could tell... but not sure.

**Comment by gabe565** [comment]
@pengi The "ignoring device" log is unrelated. That gets logged when a device is discovered that already has an active connection.

**Comment by pengi** [comment]
I got the go enviornment up and running and found the error.

Added in `internal/youtube/youtube.go` a printout of the `err` field in `QueryVideoId()`, and got the following response:

```
level=DEBUG msg=error response=<nil> err="googleapi: Error 403: YouTube Data API v3 has not been used in project XXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.Help\",\n    \"links\": [\n      {\n        \"description\": \"Google developers console API activation\",\n        \"url\": \"https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXX\"\n      }\n    ]\n  },\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.ErrorInfo\",\n    \"domain\": \"googleapis.com\",\n    \"metadata\": {\n      \"consumer\": \"projects/XXXX\",\n      \"service\": \"youtube.googleapis.com\"\n    },\n    \"reason\": \"SERVICE_DISABLED\"\n  }\n]\n, accessNotConfigured"
```

Or slightly easier formatted:
```
googleapi: Error 403: YouTube Data API v3 has not been used in project XXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developers console API activation",
        "url": "https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=XXXX"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/XXXX",
      "service": "youtube.googleapis.com"
    },
    "reason": "SERVICE_DISABLED"
  }
]
, accessNotConfigured
```

So when I simply enabled the YouTube v3 API for my API key it started working.

Think it's a case of error handling and reporting for API responses, to be helpful with outputs to point users towards how to fix it.

So now it works fine, thanks for the tool :)

**Comment by pengi** [comment]
> @pengi The "ignoring device" log is unrelated. That gets logged when a device is discovered that already has an active connection.

Assumed so :) was thinking if if wasn't multitheaded, it could be helpful to know if the retry code had exited, or something similar

**Comment by gabe565** [comment]
Sorry for the noise. I committed these changes in a single commit then decided to split them up

**Comment by gabe565** [comment]
@pengi @schumi4 I just released [v0.5.1](https://github.com/gabe565/CastSponsorSkip/releases/tag/v0.5.1)! When you get a chance, could you update and let me know if it resolves your issues?

**Comment by schumi4** [comment]
Youtube ads still don't get muted or skipped. In-video ad also didn't get skipped here.

```
Oct 03 10:33:52 DietPi systemd[1]: Started castsponsorskip.service - Skip YouTube ads and sponsorships on all local Google Cast devices.
Oct 03 10:33:54 DietPi castsponsorskip[422]: 2023/10/03 10:33:54 INFO CastSponsorSkip v0.5.1 (73f3950)
Oct 03 10:33:54 DietPi castsponsorskip[422]: 2023/10/03 10:33:54 INFO Searching for devices...
Oct 03 10:33:55 DietPi castsponsorskip[422]: 2023/10/03 10:33:55 INFO Connected to cast device. device=Küche
Oct 03 10:34:02 DietPi castsponsorskip[422]: 2023/10/03 10:34:02 INFO Connected to cast device. device=Castrop-Rauxel
Oct 03 10:34:02 DietPi castsponsorskip[422]: 2023/10/03 10:34:02 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:34:25 DietPi castsponsorskip[422]: 2023/10/03 10:34:25 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:34:38 DietPi castsponsorskip[422]: 2023/10/03 10:34:38 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:34:38 DietPi castsponsorskip[422]: 2023/10/03 10:34:38 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:34:39 DietPi castsponsorskip[422]: 2023/10/03 10:34:39 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:34:39 DietPi castsponsorskip[422]: 2023/10/03 10:34:39 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:34:41 DietPi castsponsorskip[422]: 2023/10/03 10:34:41 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:26 DietPi castsponsorskip[422]: 2023/10/03 10:35:26 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:35:39 DietPi castsponsorskip[422]: 2023/10/03 10:35:39 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:35:39 DietPi castsponsorskip[422]: 2023/10/03 10:35:39 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:39 DietPi castsponsorskip[422]: 2023/10/03 10:35:39 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:35:40 DietPi castsponsorskip[422]: 2023/10/03 10:35:40 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:43 DietPi castsponsorskip[422]: 2023/10/03 10:35:43 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:46 DietPi castsponsorskip[422]: 2023/10/03 10:35:46 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:35:46 DietPi castsponsorskip[422]: 2023/10/03 10:35:46 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:46 DietPi castsponsorskip[422]: 2023/10/03 10:35:46 INFO Video ID not found. Searching for video on YouTube... device=Castrop-Rauxel
Oct 03 10:35:47 DietPi castsponsorskip[422]: 2023/10/03 10:35:47 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
Oct 03 10:35:49 DietPi castsponsorskip[422]: 2023/10/03 10:35:49 ERROR YouTube search failed. device=Castrop-Rauxel error="search returned no videos"
```

Can provide debug logs later.

**Comment by pengi** [comment]
> @pengi @schumi4 I just released [v0.5.1](https://github.com/gabe565/CastSponsorSkip/releases/tag/v0.5.1)! When you get a chance, could you update and let me know if it resolves your issues?

It worked for me in v0.5.0 when I activated the API key actually.

But now on v0.5.1, I get somewhat better error reporting (well, I get the raw output from google API) when I don't have the key active, but I get the same error as @schumi4 when I activate the key again

```
Oct 03 09:19:21 pengi-dev castsponsorskip[21733]: 2023/10/03 09:19:21 INFO Video ID not found. Searching for video on YouTube... device="Living Room TV"
Oct 03 09:19:21 pengi-dev castsponsorskip[21733]: 2023/10/03 09:19:21 ERROR YouTube search failed. device="Living Room TV" error="search returned no videos"
Oct 03 09:19:23 pengi-dev castsponsorskip[21733]: 2023/10/03 09:19:23 ERROR YouTube search failed. device="Living Room TV" error="search returned no videos"
Oct 03 09:19:23 pengi-dev castsponsorskip[21733]: 2023/10/03 09:19:23 INFO Video ID not found. Searching for video on YouTube... device="Living Room TV"
Oct 03 09:19:25 pengi-dev castsponsorskip[21733]: 2023/10/03 09:19:25 ERROR YouTube search failed. device="Living Room TV" error="search returned no videos"
```

**Comment by pengi** [comment]
Hum... tried to checkout and rebuild from source, and get this, but doesn't work in tag v0.5.1:

```
pengi@pengi-dev:~/src/CastSponsorSkip(v0.5.1⚡) » ./run.sh                     
time=2023-10-03T09:36:00.315Z level=INFO msg="CastSponsorSkip beta"
time=2023-10-03T09:36:00.315Z level=INFO msg="Searching for devices..."
time=2023-10-03T09:36:00.390Z level=INFO msg="Connected to cast device." device="Living Room TV"
time=2023-10-03T09:36:00.890Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:10.954Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:10.983Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-10-03T09:36:10.983Z level=DEBUG msg="Searching for video ID" query="\"CHANNEL\"+intitle:\"VIDEO\""
time=2023-10-03T09:36:11.414Z level=DEBUG msg="YouTube search found video ID" device="Living Room TV" video_id=XXXXX
time=2023-10-03T09:36:11.465Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:11.964Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:12.464Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:12.964Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:13.464Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:36:13.964Z level=DEBUG msg=Update device="Living Room TV"
...
```

But when checking out v0.5.0 I get:
```
pengi@pengi-dev:~/src/CastSponsorSkip(v0.5.0⚡) » ./run.sh 
time=2023-10-03T09:38:30.995Z level=INFO msg="CastSponsorSkip beta"
time=2023-10-03T09:38:30.996Z level=INFO msg="Searching for devices..."
time=2023-10-03T09:38:33.685Z level=INFO msg="Connected to cast device." device="Living Room TV"
time=2023-10-03T09:38:34.186Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:35.256Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:35.435Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-10-03T09:38:35.435Z level=DEBUG msg="Searching for video ID" query="\"channel\"+intitle:\"video\""
time=2023-10-03T09:38:35.864Z level=INFO msg="Detected video stream." device="Living Room TV" video_id=XXXX
time=2023-10-03T09:38:35.864Z level=DEBUG msg="Request segments" url="https://sponsor.ajay.app/api/skipSegments/ba88?actionType=skip&actionType=mute&category=sponsor"
time=2023-10-03T09:38:36.127Z level=INFO msg="Found segments for video." device="Living Room TV" segments=1
time=2023-10-03T09:38:36.127Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:36.326Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:36.756Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:39.382Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:39.469Z level=INFO msg="Skipping to timestamp." device="Living Room TV" category=sponsor from=4m18s to=5m7s
time=2023-10-03T09:38:39.881Z level=DEBUG msg=Update device="Living Room TV"
time=2023-10-03T09:38:39.928Z level=INFO msg="Skipping to timestamp." device="Living Room TV" category=sponsor from=4m18s to=5m7s
time=2023-10-03T09:38:40.382Z level=DEBUG msg=Update device="Living Room TV"
```

**Comment by pengi** [comment]
I did a git bisect, and ended up on this commit introducing the error: a0de9b7ef20c43ded2eb494dfc0eb27c1cc29e1b

**Comment by schumi4** [comment]
> I did a git bisect, and ended up on this commit introducing the error: [a0de9b7](https://github.com/gabe565/CastSponsorSkip/commit/a0de9b7ef20c43ded2eb494dfc0eb27c1cc29e1b)
> 
> What I noticed is later versions with problems are missing:
> 
> ```
> time=2023-10-03T09:38:36.127Z level=INFO msg="Found segments for video." device="Living Room TV" segments=1
> ```
> 
> And that output seems to correspond to when it works or not

With "when it works", do you mean skipping in-video sponsors or skipping and muting the pre/mid-roll youtube ads?

**Comment by pengi** [comment]
> > I did a git bisect, and ended up on this commit introducing the error: [a0de9b7](https://github.com/gabe565/CastSponsorSkip/commit/a0de9b7ef20c43ded2eb494dfc0eb27c1cc29e1b)
> > What I noticed is later versions with problems are missing:
> > ```
> > time=2023-10-03T09:38:36.127Z level=INFO msg="Found segments for video." device="Living Room TV" segments=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And that output seems to correspond to when it works or not
> 
> With "when it works", do you mean skipping in-video sponsors or skipping and muting the pre/mid-roll youtube ads?

Oh right, sorry... I guess I forget about the pre/mid-roll youtube ads, since I have premium. Good call.

I can only test in-video sponsors here, so that works for me. Which means the code for detecting and searching for the videos.

**Comment by schumi4** [comment]
This might however still be related. Seeing as the evidence (very small sample size i'll admit lol) points to newer devices not having the ads muted. These are also the ones who require the whole API-key ordeal in the first place.

From my testing:
Everything works fine on older devices like OG Chromecast and Chromecast Ultra (both require no API-key).
Muting/skipping never works for Chromecast with Google TV, in-video skips work if the API lookup is successful.

**Comment by gabe565** [comment]
@schumi4 I wish I had one of these newer devices so that I could test some of this strange behavior myself. Instead, you might install [vishen/go-chromecast](https://github.com/vishen/go-chromecast) so that you can see what some of the fields are set to that differs from older devices. I'm not sure if it will give all of the data we need yet. I'll keep you posted

**Comment by gabe565** [comment]
@schumi4 If you install go-chromecast, can you run the command below, then choose your device and let an ad play? I'd love to see what gets logged. It could also be helpful if you can capture a log when the YouTube search fails.

The command is:
```shell
go-chromecast watch --debug
```

**Comment by schumi4** [comment]
I certainly can! This case however is at a friend's house so I'll have to remote in sometime next week. Maybe someone else with local access and the same issue can jump in?

Optimistic we can get this fixed though!

**Comment by schumi4** [comment]
With a heavy heart I have transistioned this case to use [iSponsorBlockTV](https://github.com/dmunozv04/iSponsorBlockTV). While I dislike the bloated feel and having to run it with docker, it works for this use case. Sticking with CSS for my local install though.

**Comment by gabe565** [comment]
@schumi4 were you ever able to grab the device status with go-chromecast? I believe I know why this is happening but unfortunately I don't have a newer Chromecast to test. I think the status field may be getting set to another number while an ad is playing

**Comment by BasVanBoven** [comment]
Hey gabe565, maybe I can help with my Chromecast with Google TV. Having the samen problems as reported by schumi4. Example output from go-chromecast while running:

`DEBU[1105] (4258)* <- 75783d53-ef11-4cbb-9d89-b780493d8144 [urn:x-cast:com.google.cast.media]: {"requestId":4258,"type":"MEDIA_STATUS","status":[{"mediaSessionId":231,"playerState":"PLAYING","playbackRate":1,"currentTime":2.264,"supportedMediaCommands":207,"volume":{"level":0,"muted":false},"activeTrackIds":[],"shuffle":false,"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Pro Bike Mechanic Tests The Cheapest Tools From Wish.com","artist":"Cade Media"},"duration":10.041},"currentItemId":1,"repeatMode":"REPEAT_OFF","items":[{"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Pro Bike Mechanic Tests The Cheapest Tools From Wish.com","artist":"Cade Media"},"duration":10.041},"itemId":1,"autoplay":true,"preloadTime":0}]}]}  package=cast`

**Comment by gabe565** [comment]
@BasVanBoven Thank you so much!

Did you grab that while an ad was playing? There should be a field called `customData`. Older devices will set `"customData":{"playerState":1081}` when an ad is playing. I hope that hasn't been removed!

**Comment by BasVanBoven** [comment]
I am afraid it has been removed. I just tested again with a larger piece of log attached, but no mention of customData anywhere. When I have more time, I will try and look into the way [iSponsorBlockTV](https://github.com/dmunozv04/iSponsorBlockTV) handles CCwGTVs (that one is working fine).

[rawlog.txt](https://github.com/gabe565/CastSponsorSkip/files/13173788/rawlog.txt)

**Comment by taviso** [comment]
> I did a git bisect, and ended up on this commit introducing the error: [a0de9b7](https://github.com/gabe565/CastSponsorSkip/commit/a0de9b7ef20c43ded2eb494dfc0eb27c1cc29e1b)
> 
> What I noticed is later versions with problems are missing:
> 
> ```
> time=2023-10-03T09:38:36.127Z level=INFO msg="Found segments for video." device="Living Room TV" segments=1
> ```
> 
> And that output seems to correspond to when it works or not

I think I have the same setup as @pengi - Google TV with a Premium subscription. Exactly the same result, 0.5.3 never skips any segments - 0.5.0 *does* work as expected.

**Comment by gabe565** [comment]
@taviso Thanks for bringing that to my attention again. I thought it had been fixed, but seems like there are still some issues. Investigating now!

**Comment by gabe565** [comment]
For some reason the search query is being built as `"channel"+intitle:"video"`, which is definitely not right.

**Comment by gabe565** [comment]
@taviso @pengi Hey! Apologies for the delay, but I believe I've fixed the issue you've been seeing. Could one of you test with the latest changes by running the code in `main`, or by using the `beta` Docker tag? I'll wait to release this until I hear back confirmation from one of you, but I'm hopeful 🤞

**Comment by pengi** [comment]
I unfortunately can't neither deny nor confirm at this point, since I get errors also on my computer. Seems that the sponsorblock API service is down. When checking it manually, I get cloudflare error code 502, at least from my location.

Therefore, I don't know if that happens also to CastSponsorSkip.

The log is at least:

```
time=2023-11-01T07:45:25.143Z level=INFO msg="CastSponsorSkip beta"
time=2023-11-01T07:45:25.144Z level=INFO msg="Searching for devices..."
time=2023-11-01T07:45:25.446Z level=INFO msg="Connected to cast device." device="Living Room TV"
time=2023-11-01T07:45:25.946Z level=DEBUG msg=Update device="Living Room TV"
time=2023-11-01T07:45:36.023Z level=DEBUG msg=Update device="Living Room TV"
time=2023-11-01T07:45:36.152Z level=INFO msg="Video ID not found. Searching for video on YouTube..." device="Living Room TV"
time=2023-11-01T07:45:36.152Z level=DEBUG msg="Searching for video ID" query="\"Actual channel here)\"+intitle:\"Actual video title here\""
time=2023-11-01T07:45:36.540Z level=DEBUG msg="YouTube search found video ID" device="Living Room TV" video_id=AYouTubeVideoIdHere
time=2023-11-01T07:45:36.644Z level=DEBUG msg=Update device="Living Room TV"
time=2023-11-01T07:45:37.144Z level=DEBUG msg=Update device="Living Room TV"
time=2023-11-01T07:45:37.644Z level=DEBUG msg=Update device="Living Room TV"
time=2023-11-01T07:45:38.145Z level=DEBUG msg=Update device="Living Room TV"
```

while standing on b182a214ce07ccaf1899b38e4b24e4ee5c5703ae

Not that I'm not used to go, so at this point I have to guess a bit of how to build. I checked out that version, then ran:
```
export CSS_YOUTUBE_API_KEY=My youtube api key here
export CSS_LOG_LEVEL=debug
export CSS_PAUSED_INTERVAL=10s
go clean
go build
go run .
```

So I hope that should rebuild everything.

That being said, it could equally well just be the sponsorblock api this time.

Unfortunately, this was probably the last time in like 2 months I can check it since I'm moving, and I'll take the TV with chromecast to one spot in an hour, and my computer in the other for a while.

**Comment by gabe565** [comment]
@pengi Thank you for testing. You helped me realize there was one final issue, but that one has also been fixed! I also tested with a friend's device which requires API lookups, and it's working great after my most recent commit!

**Comment by gabe565** [comment]
@pengi @taviso Ok I'm releasing v0.5.4 which fixes the issues you've been seeing!

Still investigating ad skip on newer devices unfortunately, but it's nice to have YouTube queries are working again

**Comment by 654456** [comment]
Can confirm the issue is present on Onn 4k tv box, and chromecast HD

**Comment by glenstewart** [comment]
I also can confirm the issue still present as of .7.2 build, on youtube app with Onn 4k tv box (Google TV)

**Comment by glenstewart** [comment]
> Can anyone see if this is improved with v0.7.3? 

Sadly, neither mute nor auto-skip are yet working with v0.7.3 when tested with the Onn 4k tv box (Google TV).  Thank you for trying - CastSponsorSkip works great on my older Chromecast devices!

**Comment by Nightwalker83** [comment]
Yeah, the skip and mute functionality does not work with my new chrome cast either. Howvever, ISponsorBlockTv works. Although, it uses the texted based setup and does not say where the device ip/id is stored whereas CSS stores everything in the docker file.

**Comment by Nightwalker83** [comment]
Does you app use the same api as iSponsorBlockTV? If so that app blocks the ads although, unlike yours the ip address for the chromecast does not seem to work.

https://github.com/dmunozv04/iSponsorBlockTV/wiki/Installation

**Comment by olinesn** [comment]
Hi all, just wanted to report that I'm observing similar behavior, so I'm documenting it here in case it's a clue for people who might circle back to this (@gabe565). 

My old Chromecast (the gray original one, 1080p) mutes the TV and completely skips YouTube ads. However my newer Chromecast with Google TV (the 4k white one with the remote) only skips sponsored content, but not the YouTube ads.

**Comment by gabe565** [comment]
@Nightwalker83 iSponsorBlockTV uses a different API called the "youtube lounge" API. Unlike the Cast API, it is a cloud API and not local to the device, but you're right that ad skip is still working for iSponsorBlockTV.

@olinesn If you or anybody in this thread doesn't mind testing something for me. Could you install [go-chromecast](https://github.com/vishen/go-chromecast?tab=readme-ov-file#installing), and when an ad is playing, run:
```shell
go-chromcast status -v
```
I'd be curious to see what the `playerState` field is set to. Currently, ad skip is triggered when that value is set to `1081`. I got that value from [here](https://github.com/vishen/go-chromecast?tab=readme-ov-file#installing) in the go-chromecast source, but it may have changed for newer devices.

**Comment by tvanicraath** [comment]
Here's the output of `go-chromecast status -v` while an ad is being played.
```
using device name=Living Room TV addr=192.168.4.103 port=8009 uuid=--redacted--
DEBU[0006] (1)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":1}  package=cast
DEBU[0006] (2)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.receiver]: {"type":"GET_STATUS","requestId":2}  package=cast
DEBU[0006] (2)sender-0 <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":2,"status":{"applications":[{"appId":"2C6A6E3D","appType":"ANDROID_TV","displayName":"YouTube","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.system"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.customdata"},{"name":"urn:x-cast:com.google.youtube.mdx"}],"senderConnected":true,"sessionId":"4dd0f3d2-3024-419f-bca8-d6e326bb52ab","statusText":"Youtube","transportId":"4dd0f3d2-3024-419f-bca8-d6e326bb52ab","universalAppId":"233637DE"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.6000000238418579,"muted":false,"stepInterval":0.03999999910593033}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0006] (3)sender-0 -> 4dd0f3d2-3024-419f-bca8-d6e326bb52ab [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":3}  package=cast
DEBU[0006] (4)sender-0 -> 4dd0f3d2-3024-419f-bca8-d6e326bb52ab [urn:x-cast:com.google.cast.media]: {"type":"GET_STATUS","requestId":4}  package=cast
DEBU[0006] (-1)* <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":0,"status":{"applications":[{"appId":"2C6A6E3D","appType":"ANDROID_TV","displayName":"YouTube","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.system"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.customdata"},{"name":"urn:x-cast:com.google.youtube.mdx"}],"senderConnected":true,"sessionId":"4dd0f3d2-3024-419f-bca8-d6e326bb52ab","statusText":"Youtube","transportId":"4dd0f3d2-3024-419f-bca8-d6e326bb52ab","universalAppId":"233637DE"}],"userEq":{},"volume":{"controlType":"attenuation","level":0.6000000238418579,"muted":false,"stepInterval":0.03999999910593033}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0006] (4)* <- 4dd0f3d2-3024-419f-bca8-d6e326bb52ab [urn:x-cast:com.google.cast.media]: {"requestId":4,"type":"MEDIA_STATUS","status":[{"mediaSessionId":10,"playerState":"PLAYING","playbackRate":1,"currentTime":1.713,"supportedMediaCommands":207,"volume":{"level":0,"muted":false},"activeTrackIds":[],"shuffle":false,"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Bapuji Hue Mandap se gayab! I FULL MOVIE | Taarak Mehta Ka Ooltah Chashmah","artist":"Taarak Mehta Ka Ooltah Chashmah"},"duration":20.021},"currentItemId":1,"repeatMode":"REPEAT_OFF","items":[{"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Bapuji Hue Mandap se gayab! I FULL MOVIE | Taarak Mehta Ka Ooltah Chashmah","artist":"Taarak Mehta Ka Ooltah Chashmah"},"duration":20.021},"itemId":1,"autoplay":true,"preloadTime":0}]}]}  package=cast
YouTube (PLAYING), title="Bapuji Hue Mandap se gayab! I FULL MOVIE | Taarak Mehta Ka Ooltah Chashmah", artist="Taarak Mehta Ka Ooltah Chashmah", time remaining=2s/20s, volume=0.60, muted=false
```

**Comment by alexbrainman** [comment]
Here's another `go-chromecast status -v` output while an ad is being played.

```
using device name=XiaomiTVBox addr=192.168.1.78 port=8009 uuid=3f240d9239ee5e2448211ebaf7ccd3d9
DEBU[0000] (1)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":1}  package=cast
DEBU[0000] (2)sender-0 -> receiver-0 [urn:x-cast:com.google.cast.receiver]: {"type":"GET_STATUS","requestId":2}  package=cast
DEBU[0000] (2)sender-0 <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":2,"status":{"applications":[{"appId":"2C6A6E3D","appType":"ANDROID_TV","displayName":"YouTube","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.system"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.customdata"},{"name":"urn:x-cast:com.google.youtube.mdx"}],"senderConnected":true,"sessionId":"6e96d5fd-8d6a-49ff-9dcc-76fb00213f12","statusText":"Youtube","transportId":"6e96d5fd-8d6a-49ff-9dcc-76fb00213f12","universalAppId":"233637DE"}],"isActiveInput":true,"isStandBy":false,"userEq":{},"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.06666667014360428}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0000] (3)sender-0 -> 6e96d5fd-8d6a-49ff-9dcc-76fb00213f12 [urn:x-cast:com.google.cast.tp.connection]: {"type":"CONNECT","requestId":3}  package=cast
DEBU[0000] (4)sender-0 -> 6e96d5fd-8d6a-49ff-9dcc-76fb00213f12 [urn:x-cast:com.google.cast.media]: {"type":"GET_STATUS","requestId":4}  package=cast
DEBU[0000] (-1)* <- receiver-0 [urn:x-cast:com.google.cast.receiver]: {"requestId":0,"status":{"applications":[{"appId":"2C6A6E3D","appType":"ANDROID_TV","displayName":"YouTube","iconUrl":"","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"},{"name":"urn:x-cast:com.google.cast.system"},{"name":"urn:x-cast:com.google.cast.cac"},{"name":"urn:x-cast:com.google.cast.customdata"},{"name":"urn:x-cast:com.google.youtube.mdx"}],"senderConnected":true,"sessionId":"6e96d5fd-8d6a-49ff-9dcc-76fb00213f12","statusText":"Youtube","transportId":"6e96d5fd-8d6a-49ff-9dcc-76fb00213f12","universalAppId":"233637DE"}],"isActiveInput":true,"isStandBy":false,"userEq":{},"volume":{"controlType":"attenuation","level":1.0,"muted":false,"stepInterval":0.06666667014360428}},"type":"RECEIVER_STATUS"}  package=cast
DEBU[0000] (4219)* <- 6e96d5fd-8d6a-49ff-9dcc-76fb00213f12 [urn:x-cast:com.google.cast.media]: {"requestId":4219,"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playerState":"PLAYING","playbackRate":1,"currentTime":7.121,"supportedMediaCommands":207,"volume":{"level":0,"muted":false},"activeTrackIds":[],"shuffle":false,"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Маша и Медведь 💥 НОВАЯ СЕРИЯ! 💥 Прыг-скок пёс 🐶🪄🌀 Коллекция мультиков про Машу","artist":"Маша и Медведь"},"duration":44.561},"currentItemId":1,"repeatMode":"REPEAT_OFF","items":[{"media":{"cont entId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Маша и Медведь 💥 НОВАЯ СЕРИЯ! 💥 Прыг-скок пёс 🐶🪄🌀 Коллекция мультиков про Машу","artist":"Маша и Медведь"},"duration":44.561}," itemId":1,"autoplay":true,"preloadTime":0}]}]}  package=cast
DEBU[0000] (-1)* <- 6e96d5fd-8d6a-49ff-9dcc-76fb00213f12 [urn:x-cast:com.google.youtube.mdx]: {"type":"mdxSessionStatus","data":{"screenId":"tfg75eio1ne0n155mbank688l3","deviceId":"8a7a7a8c-96a1-4897-952f-866b19ef2dfa"}}  package=cast
DEBU[0000] (4)* <- 6e96d5fd-8d6a-49ff-9dcc-76fb00213f12 [urn:x-cast:com.google.cast.media]: {"requestId":4,"type":"MEDIA_STATUS","status":[{"mediaSessionId":1,"playerState":"PLAYING","playbackRate":1,"currentTime":7.128,"supportedMediaCommands":207,"volume":{"level":0,"muted":false},"activeTrackIds":[],"shuffle":false,"media":{"contentId":"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Маша и Медведь 💥 НОВАЯ СЕРИЯ! 💥 Прыг-скок пёс 🐶🪄🌀 Коллекция мультиков про Машу","artist":"Маша и Медведь"},"duration":44.561},"currentItemId":1,"repeatMode":"REPEAT_OFF","items":[{"media":{"contentId" :"","streamType":"BUFFERED","metadata":{"metadataType":0,"title":"Маша и Медведь 💥 НОВАЯ СЕРИЯ! 💥 Прыг-скок пёс 🐶🪄🌀 Коллекция мультиков про Машу","artist":"Маша и Медведь"},"duration":44.561},"itemId ":1,"autoplay":true,"preloadTime":0}]}]}  package=cast
YouTube (PLAYING), title="Маша и Медведь 💥 НОВАЯ СЕРИЯ! 💥 Прыг-скок пёс 🐶🪄🌀 Коллекция мультиков про Машу", artist="Маша и Медведь", time remaining=7s/45s, volume=1.00, muted=false
```

Thank you.

Alex

**Comment by gabe565** [comment]
Thanks for the logs!

It seems the the `1081` `supportedMediaCommands` state is no longer reliable for detecting YouTube ads. YouTube seems to be masking ads as standard video playback. Looking at the logs:

- The receiver is sent the title and artist of the main video, hiding the fact that an ad is actually playing.
- Instead of restricting player commands to an ad state (`1081`), the receiver now reports standard media commands (`207`), treating the ad stream exactly like regular content.
- The durations seem to expose the ads. The first log has a total duration of only 20 seconds. The second log shows 44 seconds.

I wonder if I could fetch the real video duration using the API and compare it to what's currently playing. If the current content is much shorter, I can assume an ad is playing.

**Comment by alexbrainman** [comment]
> Thanks for the logs!

You are welcome.

I enjoy your program when my granddaughter visits me and wants to watch some YouTube on TV (I do not watch it). Before your program, I had to watch the YouTube with her to make sure I push the skip button in time. :-) Thank you.

I also noticed that your program works fine when I start the YouTube video on my Chromebook, and then cast it onto my Chromecast box. But does not work reliably when I start the YouTube on my iPhone and then cast onto Chromecast.

Let me know, if I can help you in any way.

Thank you.

Alex

**Comment by alexbrainman** [comment]
Unrelated to this issue, but I see this in the log

```
2026-03-19 14:14:55 DBG Panic during close device=XiaomiTVBox error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 16 [running]:\nruntime/debug.Stack()\n\t/home/a/go/src/runtime/debug/stack.go:26 +0x5e\ngabe565.com/castsponsorskip/internal/device.(*Device).closeApp.func1()\n\t/home/a/src/github.com/gabe565/CastSponsorSkip/internal/device/watch.go:127 +0x45\npanic({0x13e1b20?, 0x1504530?})\n\t/home/a/go/src/runtime/panic.go:860 +0x13a\nsync/atomic.(*Int32).Load(...)\n\t/home/a/go/src/sync/atomic/type.go:80\ncrypto/tls.(*Conn).Close(0xc41ec8?)\n\t/home/a/go/src/crypto/tls/conn.go:1427 +0x18\ngithub.com/vishen/go-chromecast/cast.(*Connection).Close(0x154b840?)\n\t/home/a/pkg/mod/github.com/vishen/go-chromecast@v0.3.4/cast/connection.go:84 +0x89\ngithub.com/vishen/go-chromecast/application.(*Application).Close(0x47460f?, 0x2f?)\n\t/home/a/pkg/mod/github.com/vishen/go-chromecast@v0.3.4/application/application.go:447 +0x11e\ngabe565.com/castsponsorskip/internal/device.(*Device).closeApp(0x31816c589808?)\n\t/home/a/src/github.com/gabe565/CastSponsorSkip/internal/device/watch.go:131 +0x5c\ngabe565.com/castsponsorskip/internal/device.(*Device).Close(0x31816c6ba540)\n\t/home/a/src/github.com/gabe565/CastSponsorSkip/internal/device/watch.go:120 +0x8f\ngabe565.com/castsponsorskip/cmd.run.func1()\n\t/home/a/src/github.com/gabe565/CastSponsorSkip/cmd/cmd.go:89 +0x105\nsync.(*WaitGroup).Go.func1()\n\t/home/a/go/src/sync/waitgroup.go:258 +0x4a\ncreated by sync.(*WaitGroup).Go in goroutine 1\n\t/home/a/go/src/sync/waitgroup.go:238 +0x73\n"
```

I am using `castsponsorskip version beta (f51d5e7e)`.

Alex
