### ISSUE TITLE
[Feature] Expand scope to include Youtube TV applications

### ISSUE THREAD

**Issue by kmaid** [gabe565/CastSponsorSkip#70]
This project looks amazing!

I was testing this project and was happy with how it worked for casting however I was quite confused as to why it didn't work for Youtube TV apps like isponsorblocktv. Is it possible to expand this project's scope to cover both casting and YouTube TV Apps? 

In the meantime, I am running both projects but am concerned they will clash. 

The other problem I ran into was Advert muting doesn't work on my TV. CastSponsorSkip attempts to mute the TV however a grey alert bubble on the TV says something along the lines of using the remote to control the TV volume. I suspect this is due to setting the volume to 0 rather than using "Mute". My TV CEC implementation only provides volume increase, decrease and mute and will complain if I use the volume slider within the Chromecast remote app on my phone with a similar message. This functionality does work on isponsorblocktv.

Thanks for all the hard work and I hope this makes sense!

**Comment by gabe565** [comment]
@kmaid Do you mean YouTube's TV streaming offering, or the YouTube app on a TV? Because it works with the latter, but you'll need to generate a YouTube API key. I use it with an Nvidia Shield and it was broken for the past couple of weeks due to a YouTube bug, but it seems to be fixed now!

**Comment by kmaid** [comment]
I mean the Youtube TV App. I have generated a Youtube APII key for the other project. I will retry everything shortly

**Comment by gabe565** [comment]
#71 has been been resolved by the latest YouTube app, so it should work for you again!

**Comment by kmaid** [comment]
it has not resolved it for me. I checked for updates on the Chromecast YouTube app and none were available. I stopped ISponsorBlock and recreated CastSponsorSkip.

```2024/03/01 20:15:14 INFO Found segments for video. device="Living Room TV" segments=1
2024/03/01 20:15:43 INFO Video ID not set. Searching YouTube for video ID... device="Living Room TV"
2024/03/01 20:15:44 INFO Detected video stream. device="Living Room TV" video_id=Jt1teDSV0Y4
2024/03/01 20:15:44 INFO No segments found for video. device="Living Room TV" video_id=Jt1teDSV0Y4
```

It detected a video playing but did not skip any of the advertisements on the youtube app.


Casting video works as before. Ads are skipped however muting adverts fails like the photo below 
![IMAGE 2024-03-01 20:38:16](https://github.com/gabe565/CastSponsorSkip/assets/1936253/9888b2a5-5129-4fa1-8241-1978a1d64236)

**Comment by gabe565** [comment]
"No segments found for video" means SponsorBlock doesn't know of any sponsored segments. I checked the video ID in your logs and can confirm there are no segments available. 
<img width="262" alt="image" src="https://github.com/gabe565/CastSponsorSkip/assets/7717888/b3cad73e-1845-4563-8c8e-13af78906207">

Hmm the mute issue is an interesting one. I hadn't thought about HDMI-CEC devices that don't support volume. For some reason, I thought the Chromecast could still mute. I'm not sure if there's anything I can do here, since the only available mute function obviously just shows a toast. I'll let you know if I think of anything!

**Comment by ReX1983** [comment]
> "No segments found for video" means SponsorBlock doesn't know of any sponsored segments. I checked the video ID in your logs and can confirm there are no segments available.

Any idea why I get always no segments fouund for video? 

I am running the YouTube app on the Chromecast TV 4K and it never managed to skip a single add. I have added they key, but no change. 

This is an example from a few minutes ago:

```
2024/04/22 20:09:45 INFO Detected video stream. device="Living Room TV" video_id=ZKnf4HfGGZc
2024/04/22 20:09:47 INFO No segments found for video. device="Living Room TV" video_id=ZKnf4HfGGZc


```
